### ISSUE TITLE
THX

### ISSUE THREAD

**Issue by caecos** [hwpfeil/plugins#2]
Just want to say thank you for updating sources from 0.5 to 0.6

**Comment by hwpfeil** [comment]
You're welcome! I was planning on announcing these after I compiled and tested them on linux.
Delayed by jury duty in Federal Court.... (It's not like Perry Mason, they don't defend the innocent by revealing the guilty party in the fourth act.)

**Comment by caecos** [comment]
Many thanks for all your work...it's appreciated…
